-- Seeded from the 103 distinct course names found across the Fall 2026 report cards.
-- These are BEST GUESSES from the course titles. Review them in the portal's
-- Course Rules panel before trusting a run -- especially the borderline PE-ish
-- ones: Strgth/Exercise, Power Walking, Pep Squad, Online PE-MED, Tennis.
INSERT OR IGNORE INTO courses (name, display, value) VALUES
  ('a cappella a', 'A Cappella A', 'Regular'),
  ('algebra 1', 'Algebra 1', 'Regular'),
  ('algebra 1a d', 'Algebra 1A D', 'Regular'),
  ('algebra 2', 'Algebra 2', 'Regular'),
  ('ap art his', 'AP Art His', 'AP'),
  ('ap biology', 'AP Biology', 'AP'),
  ('ap calc bc', 'AP Calc BC', 'AP'),
  ('ap calculus', 'AP Calculus', 'AP'),
  ('ap chem', 'AP Chem', 'AP'),
  ('ap cmptscia', 'AP CmptSciA', 'AP'),
  ('ap cs principle', 'AP CS Principle', 'AP'),
  ('ap environ sci', 'AP Environ Sci', 'AP'),
  ('ap eur his', 'AP Eur His', 'AP'),
  ('ap french 4', 'AP French 4', 'AP'),
  ('ap humangeog', 'AP HumanGeog', 'AP'),
  ('ap lang/cmp', 'AP Lang/Cmp', 'AP'),
  ('ap physics 1', 'AP Physics 1', 'AP'),
  ('ap physics 2', 'AP Physics 2', 'AP'),
  ('ap psych', 'AP Psych', 'AP'),
  ('ap research', 'AP Research', 'AP'),
  ('ap seminar 1', 'AP Seminar 1', 'AP'),
  ('ap spnsh 4', 'AP Spnsh 4', 'AP'),
  ('ap statistics', 'AP Statistics', 'AP'),
  ('ap us history', 'AP US History', 'AP'),
  ('architectdesign', 'ArchitectDesign', 'Regular'),
  ('ath basketbl -b', 'Ath Basketbl -B', 'Inapplicable'),
  ('ath basketbl -g', 'Ath Basketbl -G', 'Inapplicable'),
  ('ath football', 'Ath Football', 'Inapplicable'),
  ('ath golf g', 'Ath Golf G', 'Inapplicable'),
  ('ath lacrosse-b', 'Ath Lacrosse-B', 'Inapplicable'),
  ('ath lacrosse-g', 'Ath Lacrosse-G', 'Inapplicable'),
  ('ath soccer -b', 'Ath Soccer -B', 'Inapplicable'),
  ('ath soccer -g', 'Ath Soccer -G', 'Inapplicable'),
  ('ath softball', 'Ath Softball', 'Inapplicable'),
  ('ath swimming/b', 'Ath Swimming/B', 'Inapplicable'),
  ('ath swimming/g', 'Ath Swimming/G', 'Inapplicable'),
  ('ath tennis -b', 'Ath Tennis -B', 'Inapplicable'),
  ('ath tennis -g', 'Ath Tennis -G', 'Inapplicable'),
  ('ath track/fld-b', 'Ath Track/Fld-B', 'Inapplicable'),
  ('ath track/fld-g', 'Ath Track/Fld-G', 'Inapplicable'),
  ('ath volleybl -b', 'Ath Volleybl -B', 'Inapplicable'),
  ('ath volleybl -g', 'Ath Volleybl -G', 'Inapplicable'),
  ('avid 10', 'AVID 10', 'Regular'),
  ('avid 11', 'AVID 11', 'Regular'),
  ('biology', 'Biology', 'Regular'),
  ('biotechnology', 'Biotechnology', 'Regular'),
  ('businessmgmtent', 'BusinessMgmtEnt', 'Regular'),
  ('chamberorchestr', 'ChamberOrchestr', 'Regular'),
  ('chemistry', 'Chemistry', 'Regular'),
  ('college&career', 'College&Career', 'Regular'),
  ('concert band', 'Concert Band', 'Regular'),
  ('creative wri', 'Creative Wri', 'Regular'),
  ('digital photo', 'Digital Photo', 'Regular'),
  ('drama adv', 'Drama Adv', 'Regular'),
  ('dramamusiccomfa', 'DramaMusicComFA', 'Regular'),
  ('dramamusiccompe', 'DramaMusicComPE', 'Regular'),
  ('draw/paint', 'Draw/Paint', 'Regular'),
  ('english 1', 'English 1', 'Regular'),
  ('english 2', 'English 2', 'Regular'),
  ('english 3', 'English 3', 'Regular'),
  ('fashiondesnadv', 'FashionDesnAdv', 'Regular'),
  ('forensicscience', 'ForensicScience', 'Regular'),
  ('french 1', 'French 1', 'Regular'),
  ('french 2', 'French 2', 'Regular'),
  ('french 3', 'French 3', 'Regular'),
  ('geometry', 'Geometry', 'Regular'),
  ('health', 'Health', 'Regular'),
  ('hon precalculus', 'Hon Precalculus', 'Honors'),
  ('honors biology', 'Honors Biology', 'Honors'),
  ('honorsalg2trig', 'HonorsAlg2Trig', 'Honors'),
  ('honorschemistry', 'HonorsChemistry', 'Honors'),
  ('honorsenglish1', 'HonorsEnglish1', 'Honors'),
  ('honorsenglish2', 'HonorsEnglish2', 'Honors'),
  ('jazz ensemble', 'Jazz Ensemble', 'Regular'),
  ('medical core', 'Medical Core', 'Regular'),
  ('medical innovat', 'Medical Innovat', 'Regular'),
  ('mixed chorus', 'Mixed Chorus', 'Regular'),
  ('model un', 'Model UN', 'Regular'),
  ('newspaper', 'Newspaper', 'Regular'),
  ('online pe-med', 'Online PE-MED', 'Inapplicable'),
  ('pe activities', 'PE Activities', 'Inapplicable'),
  ('pe activities 9', 'PE Activities 9', 'Inapplicable'),
  ('pep squad', 'Pep Squad', 'Inapplicable'),
  ('percussionensem', 'PercussionEnsem', 'Regular'),
  ('physics', 'Physics', 'Regular'),
  ('power walking', 'Power Walking', 'Inapplicable'),
  ('precalculus', 'Precalculus', 'Regular'),
  ('rapid prototype', 'Rapid Prototype', 'Regular'),
  ('roboticsfundame', 'RoboticsFundame', 'Regular'),
  ('sch service', 'Sch Service', 'Regular'),
  ('sinfoniaorchest', 'SinfoniaOrchest', 'Regular'),
  ('sp spkrs 1', 'Sp Spkrs 1', 'Regular'),
  ('spanish 1', 'Spanish 1', 'Regular'),
  ('spanish 2', 'Spanish 2', 'Regular'),
  ('spanish 3', 'Spanish 3', 'Regular'),
  ('spanish 4', 'Spanish 4', 'Regular'),
  ('stagecraftbasic', 'StagecraftBasic', 'Regular'),
  ('strgth/exercise', 'Strgth/Exercise', 'Inapplicable'),
  ('student govt', 'Student Govt', 'Regular'),
  ('tennis', 'Tennis', 'Inapplicable'),
  ('us history', 'US History', 'Regular'),
  ('world history', 'World History', 'Regular'),
  ('yearbook', 'Yearbook', 'Regular');
