name = "csfeligibility"
pages_build_output_dir = "public"
compatibility_date = "2026-08-24"

[[d1_databases]]
binding = "DB"
database_name = "csf-eligibility-settings"
database_id = "5713f8c0-683f-4a6f-a821-c5e7fd81c0d5"
